# LiteLLM Configuration
# This file defines model configurations and routing rules

# Model definitions
model_list:
  # OpenAI Models - Latest and Best
  - model_name: gpt-4o
    litellm_params:
      model: gpt-4o
      api_key: ${OPENAI_API_KEY}
      
  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: ${OPENAI_API_KEY}
      
  - model_name: o1-preview
    litellm_params:
      model: o1-preview
      api_key: ${OPENAI_API_KEY}
      
  - model_name: o1-mini
    litellm_params:
      model: o1-mini
      api_key: ${OPENAI_API_KEY}
      
  # Legacy OpenAI Models (still supported)
  - model_name: gpt-4-turbo
    litellm_params:
      model: gpt-4-turbo
      api_key: ${OPENAI_API_KEY}
      
  - model_name: gpt-4
    litellm_params:
      model: gpt-4
      api_key: ${OPENAI_API_KEY}

  # Anthropic Claude Models - Latest and Best
  - model_name: claude-3-5-sonnet-20241022
    litellm_params:
      model: claude-3-5-sonnet-20241022
      api_key: ${ANTHROPIC_API_KEY}
      
  - model_name: claude-3-opus-20240229
    litellm_params:
      model: claude-3-opus-20240229
      api_key: ${ANTHROPIC_API_KEY}
      
  - model_name: claude-3-5-sonnet-20240620
    litellm_params:
      model: claude-3-5-sonnet-20240620
      api_key: ${ANTHROPIC_API_KEY}
      
  - model_name: claude-3-haiku-20240307
    litellm_params:
      model: claude-3-haiku-20240307
      api_key: ${ANTHROPIC_API_KEY}

  # Azure OpenAI Models
  - model_name: azure-gpt-4
    litellm_params:
      model: azure/gpt-4
      api_base: ${AZURE_API_BASE}
      api_key: ${AZURE_API_KEY}
      api_version: ${AZURE_API_VERSION}

  # AWS Bedrock Models
  - model_name: bedrock-claude-3-opus
    litellm_params:
      model: bedrock/anthropic.claude-3-opus-20240229-v1:0
      aws_access_key_id: ${AWS_ACCESS_KEY_ID}
      aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
      aws_region_name: ${AWS_REGION_NAME}

  - model_name: bedrock-claude-3-sonnet
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0
      aws_access_key_id: ${AWS_ACCESS_KEY_ID}
      aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
      aws_region_name: ${AWS_REGION_NAME}

  # Google Vertex AI Models
  - model_name: vertex-gemini-pro
    litellm_params:
      model: vertex_ai/gemini-pro
      vertex_project: ${VERTEX_PROJECT}
      vertex_location: ${VERTEX_LOCATION}

# General settings
litellm_settings:
  # Fallback models if primary fails
  fallbacks:
    - model: gpt-4o
      fallback_models:
        - gpt-4-turbo
        - claude-3-5-sonnet-20241022
    - model: claude-3-5-sonnet-20241022
      fallback_models:
        - claude-3-opus-20240229
        - gpt-4o

  # Set default values
  set_verbose: false
  
  # Request timeout in seconds
  request_timeout: 600
  
  # Max retries
  num_retries: 3
  
  # Context window fallbacks
  context_window_fallbacks:
    - model: gpt-4o
      fallback_models:
        - claude-3-5-sonnet-20241022
        - claude-3-opus-20240229

# Router settings
router_settings:
  routing_strategy: simple-shuffle  # simple-shuffle, least-busy, latency-based
  
  # Model aliases
  model_aliases:
    gpt4: gpt-4o
    gpt4o: gpt-4o
    gpt4o-mini: gpt-4o-mini
    o1: o1-preview
    claude: claude-3-5-sonnet-20241022
    claude-sonnet: claude-3-5-sonnet-20241022
    claude-opus: claude-3-opus-20240229
    claude-haiku: claude-3-haiku-20240307

# Success callbacks for logging
success_callback: ["langfuse"]

# Failure callbacks for error tracking
failure_callback: ["langfuse"]
