# LiteLLM Configuration
# This file defines model configurations and routing rules

# Model definitions
model_list:
  # OpenAI Models - Latest and Best (October 2025)
  - model_name: gpt-5
    litellm_params:
      model: gpt-5
      api_key: ${OPENAI_API_KEY}
      
  - model_name: gpt-5-mini
    litellm_params:
      model: gpt-5-mini
      api_key: ${OPENAI_API_KEY}
      
  - model_name: gpt-5-nano
    litellm_params:
      model: gpt-5-nano
      api_key: ${OPENAI_API_KEY}
      
  - model_name: gpt-4.1
    litellm_params:
      model: gpt-4.1
      api_key: ${OPENAI_API_KEY}
      
  - model_name: gpt-4.1-mini
    litellm_params:
      model: gpt-4.1-mini
      api_key: ${OPENAI_API_KEY}
      
  - model_name: gpt-4.5
    litellm_params:
      model: gpt-4.5
      api_key: ${OPENAI_API_KEY}

  # Anthropic Claude Models - Latest and Best (October 2025)
  - model_name: claude-sonnet-4-5
    litellm_params:
      model: claude-sonnet-4-5-20250929
      api_key: ${ANTHROPIC_API_KEY}
      
  - model_name: claude-opus-4-1
    litellm_params:
      model: claude-opus-4-1
      api_key: ${ANTHROPIC_API_KEY}
      
  - model_name: claude-haiku-4-5
    litellm_params:
      model: claude-haiku-4-5
      api_key: ${ANTHROPIC_API_KEY}

  # Azure OpenAI Models
  - model_name: azure-gpt-4
    litellm_params:
      model: azure/gpt-4
      api_base: ${AZURE_API_BASE}
      api_key: ${AZURE_API_KEY}
      api_version: ${AZURE_API_VERSION}

  # AWS Bedrock Models
  - model_name: bedrock-claude-3-opus
    litellm_params:
      model: bedrock/anthropic.claude-3-opus-20240229-v1:0
      aws_access_key_id: ${AWS_ACCESS_KEY_ID}
      aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
      aws_region_name: ${AWS_REGION_NAME}

  - model_name: bedrock-claude-3-sonnet
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0
      aws_access_key_id: ${AWS_ACCESS_KEY_ID}
      aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
      aws_region_name: ${AWS_REGION_NAME}

  # Google Vertex AI Models
  - model_name: vertex-gemini-pro
    litellm_params:
      model: vertex_ai/gemini-pro
      vertex_project: ${VERTEX_PROJECT}
      vertex_location: ${VERTEX_LOCATION}

# General settings
litellm_settings:
  # Fallback models if primary fails
  fallbacks:
    - model: gpt-5
      fallback_models:
        - gpt-4.1
        - claude-sonnet-4-5
    - model: claude-sonnet-4-5
      fallback_models:
        - claude-opus-4-1
        - gpt-5

  # Set default values
  set_verbose: false
  
  # Request timeout in seconds
  request_timeout: 600
  
  # Max retries
  num_retries: 3
  
  # Context window fallbacks
  context_window_fallbacks:
    - model: gpt-5
      fallback_models:
        - gpt-4.1
        - claude-sonnet-4-5

# Router settings
router_settings:
  routing_strategy: simple-shuffle  # simple-shuffle, least-busy, latency-based
  
  # Model aliases
  model_aliases:
    gpt5: gpt-5
    gpt4: gpt-4.1
    claude: claude-sonnet-4-5
    claude-sonnet: claude-sonnet-4-5
    claude-opus: claude-opus-4-1
    claude-haiku: claude-haiku-4-5

# Success callbacks for logging
success_callback: ["langfuse"]

# Failure callbacks for error tracking
failure_callback: ["langfuse"]
